# example netlify.toml
[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps" # force install for histoire https://github.com/histoire-dev/histoire/pull/569

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    ## Content-Security-Policy = "default-src 'self'; script-src 'nonce-swyx'; img-src *"
    # in loving memory
    X-Clacks-Overhead = "GNU Terry Pratchett"
